name: PHP Composer

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: ~
permissions:
  contents: read

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
    - name: Conventional Commits Checker
      uses: netodevel/conventional-commits-checker@v1.0.1
  linter:  
    runs-on: ubuntu-latest

    steps:
            
    - uses: actions/checkout@v4
    - name: "Install PHP with extensions"
      uses: "shivammathur/setup-php@v2"
    -
      name: "Install Composer dependencies"
      uses: "ramsey/composer-install@v2"
    - name: PHP CS Fixer
      run: vendor/bin/php-cs-fixer check --diff
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict
    - name: "Install PHP with extensions"
      uses: "shivammathur/setup-php@v2"
    -
      name: "Install Composer dependencies"
      uses: "ramsey/composer-install@v2"
      
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
    
    
  
